### ISSUE TITLE
Test results before making release

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ubergraph2asct#5]
@anitacaron  to provide examples for @dosumis & @aleixpuigb to review.

**Comment by anitacaron** [comment]
Instead of you installing poetry, etc., to run the command, I've updated the test examples for you.

Please check the [seed terms](https://github.com/hubmapconsortium/ubergraph2asct/blob/main/test/eye-seed.txt), the [properties file](https://github.com/hubmapconsortium/ubergraph2asct/blob/main/test/properties.txt) and the [ASCT result](https://github.com/hubmapconsortium/ubergraph2asct/blob/main/test/eye-asct.csv) for the Eye.

~Please ignore the column header. The order in the table is proper; it's just that the number of AS is not correct. I'm working to fix that.~

**Comment by aleixpuigb** [comment]
As in the neuron there are many neurons, specially in the retina, 'has soma location' substitutes 'part of'. Therefore, these retinal neurons can't be mapped to retina. Also, many CT1 can't be mapped to the eye because are general terms, but this is because they should not be used for the tables.
